services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-app:latest
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
