services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-app:latest
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://52.22.235.213:3306/dbContenido?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: DuocUC..2025

