name: build-and-deploy-jar-only

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Compilar y generar .jar
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar proyecto (crea .jar en target/)
        run: mvn clean package

      - name: Renombrar jar a app.jar
        run: |
          mkdir dist
          cp target/*.jar dist/app.jar

      - name: Copiar app.jar y archivos Docker a EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: |
            dist/app.jar
            Dockerfile
            docker-compose.yml
          target: /home/ubuntu/app/

      - name: Levantar contenedor en EC2 con Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/app
            sudo docker compose down
            sudo docker compose up -d --build
