name: build-and-deploy-jar-only

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Compilar y desplegar Spring Boot en EC2
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar proyecto con Maven
        run: mvn clean package

      - name: Crear carpeta dist y mover el .jar
        run: |
          mkdir -p dist
          cp target/*.jar dist/app.jar

      - name: Verificar archivos generados
        run: ls -la dist

      - name: Copiar archivos al servidor EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: .
          target: /home/ubuntu/app/

      - name: Desplegar con Docker Compose en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/app
            docker compose down
            docker compose up -d --build
            docker compose ps
